# Generated by Django 4.0.3 on 2022-03-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='image',
        ),
    ]
