# Generated by Django 4.0.3 on 2022-03-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_catalog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='images/catalog')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
            ],
            options={
                'ordering': ('catalog', 'name'),
                'index_together': {('slug',)},
            },
        ),
    ]
