# Generated by Django 4.0.3 on 2022-03-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_typeclothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
                ('full_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('info', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('special', models.BooleanField(default=False)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.typeclothes')),
            ],
            options={
                'ordering': ('name', '-created'),
            },
        ),
    ]
