# Generated by Django 4.0.3 on 2022-03-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
    ]
