# Generated by Django 4.0.3 on 2022-07-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_typeclothes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeclothes',
            name='category',
        ),
    ]
