# Generated by Django 4.0.3 on 2022-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_color_alter_catalog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Размер'),
        ),
    ]
