# Generated by Django 4.0.3 on 2022-07-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='css_tag',
            field=models.CharField(default='#ffff', max_length=50),
        ),
    ]
