# Generated by Django 4.0.3 on 2022-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_color_css_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='shop.size', verbose_name='Размеры'),
        ),
    ]
