# Generated by Django 4.0.3 on 2022-08-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='novaya_pochta',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Самовывоз', 'Самовывозом'), ('Доставка', 'Доставкой'), ('Новой почтой', 'Доставка Новой почтой')], max_length=50, verbose_name='Способ доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Наличными', 'Оплата наличными'), ('Картой', 'Оплата картой'), ('Наложенный платеж', 'Наложенным платежём')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
