# Generated by Django 4.0.3 on 2022-08-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_novaya_pochta_alter_order_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Заказ активен?'),
        ),
    ]
